---
logs:
  json: false
metrics:
  endpoint: 127.0.0.1:8001
tokio:
  worker_threads: 4
  affinity: 0-3
source:
  rpc:
    url: http://127.0.0.1:8899/
    timeout: 30s
    concurrency: 10
  stream:
    source: richat # valid: richat, dragons_mouth
    endpoint: http://127.0.0.1:10000
    ca_certificate: null
    connect_timeout: null
    buffer_size: null
    http2_adaptive_window: null
    http2_keep_alive_interval: null
    initial_connection_window_size: null
    initial_stream_window_size: null
    keep_alive_timeout: null
    keep_alive_while_idle: false
    tcp_keepalive: 15s
    tcp_nodelay: true
    timeout: null
    max_decoding_message_size: 16_777_216 # 16MiB
    compression:
      accept: ["gzip", "zstd"]
      send: ["gzip", "zstd"]
    x_token: null
storage:
